sudo: required
env:
  global:
    - secure: w+30LNDNrKGZUrO7tlevymcPwcHejDYqA2Ytq9JUiXZdisB1yDa5nfCb3zWga1X8TL83z9o1sdHklgXsOCUYm6Adr1a+w8FhfZ69g861zkJBZJCDeKYtng74mpS/d7O+E5lF9Fb8SnCpnO6rdLwNCf7hq5Kap5pEmOrbjKYpDpitcTtDFdToTHasP5OTANxVIWy66j2qUtF6R6x4oP8BUqORTfn8mwiRxhCJCSEMnmq+nJ/23Tul4kmCw5VXZZ7O697Bw0R1rUO2PzK6gYEy2M7hBcPjcgg3Yyr4jLonEld+ULNL8/Qj16hSbpt7ARHG3GAgkly+AzrVgI5CKUEzGNCYG5RTedx9fDBefWajA7nMMQGKe6WskJOkOolu0mTngUUtk8xRsks7mIZGp8vXdscOxGeUfYxJ72qSJw9nhOIU7VVsLiEcPOyCO9Iv8+O3P9Y2y0oTXoREJc54nvJG8bnmBOxz5CYE9sU1P16wB/uHkMZoE+CFMv9l1MJZaGN9DmK50seZGhzrhpZA8Sl6siCUlLt9BR0ZZW0kJWqLVznIRkDLgFWu2ZBEcF/IDVIbrE5iuqItUIPUJDNMOTRiii+fX9LTaubJUAwzGi4ecZCbqpmSSidKOoR5hz0bX9ZwSyzVQJyIbzNLDyQJGQG0UbcMv1mxVAH2boCDuJ76So8=
    - SPATIAL_LIB_DIR=${TRAVIS_BUILD_DIR}/dependencies
matrix:
  include: 
    - os: linux
      dist: xenial
    # Build was exceeding 10 mins - re-evaluate when Windows is more stable on travis.
    # - os: windows
    - os: osx
language: rust
rust:
  - 1.31.1
before_install:
- set -e
install:
- "./ci/install.sh"
script:
- "./ci/lint.sh"
- "./ci/build-test.sh"
