sudo: required
env:
  global:
    # Spatial OAuth token
    - secure: "NNtu23ZKt0p9MsSMgzOmVAvsX2tsom0Bfemu4XMUZbb1Dja/Hf0fQbZrtdBk3QI58qnKXe+PRTcRgpNBj8nlN2EQXSbkkzUi64yyXleOShnDZW0xF978BwDxmij08aHtC5Wy6cFMkrOLSxRa9q0yaJOfl3vlSXRCAo3iIpUZan2pZhtM6YNmqUyWHDgZ3PMs52lX8IVm0eRys4GAezGpJ53zZCd6wFGcT42OYi39kwfFlnpOtlFaR9vxKXN6SdnQOqBnJHILxs6DT38Fqezy5xnBWIENBnMlke21SFMgb6XmeyaC5qstIAqg4NkfX2VIhn63YMLwciy6FSVI1RrGXCKpaQMDB1sWtWfm+33LpetpIiIE4PZ0sdT/NhssqrskT2IyPODHu8/ROdMlwp6MurKw8E4XPfstCTl7phvRLHzMs1YrqrTFzDtJthu86fe9E4usD2gegF78UrPQm0s5ZstiIS8l1IaS/JroydO7HamIrap5xvQn0bM14GVRN8jP6m6n2TNW7ib/t+k4oM7QbxxthIGUKl8gyxoTZnnYD6G2xZlrZTlz/jVH5aIqiUbz5nsi0utqRhtOqHJ/+5ME7rJkI+emOgpnYnhNPCrfYabu3hEXidLQjXlnOb3SwCiWNsbtNqhY9XwTSwA6N+j9CmfTHADPG7jiWBtkFUb2TeE="
    - SPATIAL_LIB_DIR=${TRAVIS_BUILD_DIR}/dependencies

language: rust

matrix:
  include:
    - os: linux
      dist: xenial
      rust: stable

    - os: linux
      dist: xenial
      rust: beta

    - os: linux
      dist: xenial
      rust: nightly

    - os: osx
      rust: stable

    - os: windows
      rust: stable

  allow_failures:
    - os: windows
    - rust: nightly

before_install:
- set -e

install:
- "./ci/install.sh"

script:
- "./ci/lint.sh"
- "./ci/build-test.sh"
