jobs:
- job: ${{ parameters.name }}
  pool: 
    - vmImage: ${{ parameters.vmImage }}
  steps: 
    - ${{ if ne(parameters.name, 'Windows') }}:
      - script: | 
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          export PATH="$HOME/.cargo/bin:$PATH"
          echo "##vso[task.setvariable variable=PATH]$PATH"
          rustc -Vv
          cargo -V
        display: Install Rust
    - ${{ if eq(parameters.name, 'Windows') }}:
      - script: | 
            curl -sSf -o rustup-init.exe https://win.rustup.rs
            rustup-init.exe -y --default-toolchain nightly
            set PATH=%PATH%;%USERPROFILE%\.cargo\bin
            echo "##vso[task.setvariable variable=PATH]%PATH%;%USERPROFILE%\.cargo\bin"
            rustc -Vv
            cargo -V
        display: Install Rust
