[package]
name = "spatialos-sdk-test-suite"
version = "0.0.0"
authors = ["Jamie Brynes <jamiebrynes7@gmail.com>"]
edition = "2018"

[dependencies]
spatialos-sdk = { path = "../spatialos-sdk"}
approx = "0.3"
