[package]
name = "cargo-spatial-package-downloader"
version = "0.1.0"
authors = ["Jamie Brynes <jamiebrynes7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.1"
