on: [push]

name: Premerge checks

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install spatial
        uses: jamiebrynes7/get-spatial-cli-action@v1
        with:
          version: 20190416.094616.a865bb5b54
          oauth_token: ${{ secrets.SPATIAL_OAUTH_TOKEN }}

      - name: Install cargo-spatial
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path ./cargo-spatial --force

      - name: Install SpatialOS C API dependencies
        uses: actions-rs/cargo@v1
        with:
          command: spatial
          args: download sdk --sdk-version 14.0.0
        env:
          SPATIAL_LIB_DIR: "dependencies"
      
      - name: Build crates
        uses: actions-rs/cargo@v1
        with:
          command: build
        env:
          SPATIAL_LIB_DIR: "dependencies"        
